server:
  port: 8081
  max-http-header-size: 81920
  servlet:
      context-path: /mola
      compression:
        enabled: true
        mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms?serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 20
      min-idle: 3
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: select 'x'
      validation-query-timeout: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      filters: stat,wall
      web-stat-filter:
        enabled: false
        principal-cookie-name: USER_COOKIE
        principal-session-name: USER_SESSION
        session-stat-enable: false
        url-pattern: /*
        exclusions: .js,.css,.png,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /sqlMonitor/*
        login-username: admin
        login-password: (*()KJKmdindudruid#032*#%$#@$jdhs
        allow:
        deny:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000s
    password:
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 10000s
  # 定时任务配置器，定时生成某些页面
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler00 #调度器实例名称
            instanceId: AUTO #调度器实例编号自动生成
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化方式配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #持久化方式配置数据驱动，MySQL数据库
            tablePrefix: qrtz_ #quartz相关数据表前缀名
            isClustered: false #开启分布式部署
            useProperties: false #配置是否使用
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool #线程池实现类
            threadCount: 7 #执行最大并发线程数量
            threadPriority: 5 #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #配置是否启动自动加载数据库内的定时任务，默认true
    job-store-type: jdbc


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.thinkcms.*.entity;com.thinkcms.*.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-config:
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      table-underline: true
      #数据库大写下划线
      #capital-mode: true
      # Sequence序列接口实现类配置
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
       #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
       #自定义填充策略接口实现
       #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

fdfs:
  so-timeout: 6000
  connect-timeout: 6000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - xxx.xxx.xxx.xxx:22122

thinkitcms:
  sourceRootPath: E:\bnews1
  sourceTempPath: ${thinkitcms.sourceRootPath}/templates
  sourceFragmentFilePath: ${thinkitcms.sourceTempPath}/fragment
  fileResourcePath: ${thinkitcms.sourceRootPath}/fileresource/
  siteStaticFileRootPath: ${thinkitcms.sourceRootPath}/webfile
  siteDomain: http://127.0.0.1/
  serverApi: http://127.0.0.1:8081
  siteFdfsDomain: http://xxx.xxx.xx.xxx/
  baiDuTongJiUrl: https://tongji.baidu.com/web/29891141/overview/index
  baiDuTongjiUrlM: https://tongji.baidu.com/m/welcome#/report/14347968
  allowMultiLogin: true
  startSolr: false
  licensePath: ${thinkitcms.sourceRootPath}/license
  pluginsBasePath: ${thinkitcms.sourceRootPath}/plugins
  oss:
     #七牛云 oss 配置 注意 bucket 设置为 公共读
#    accessKey: xxxxx
#    secretKey: xxxxx
#    prefix: http://q6ijw01cl.bkt.clouddn.com/
#    bucket: thinkitcms
    #阿里云 oss 配置 注意 bucket 设置为 公共读
    accessKey: xxxxx
    secretKey: xxxxx
    endpoint: oss-cn-qingdao.aliyuncs.com
    bucket: thinkitcms
    prefix: https://${thinkitcms.oss.bucket}.${thinkitcms.oss.endpoint}/

#允许放行的地址在路由中不拦截
permission:
  application:
    - appName: ${spring.application.name}
      authc:
        - /minapp/user/updateInfo
        - /minapp/user/getInfo
        - /user/info
        - /user/list
        - /common
      ignore:
        - /error/**
        - /favicon.ico
        - /socket/**
        - /stomp/**
        - /api/**
        - /sqlMonitor/**
        - /plugins/**
        - /thinkitcmsresource/**
logging:
  file: cms.log
  path: E:/port/log